export const pageMessageActionTypes = {
    SHOW_MESSAGE: 'SHOW_MESSAGE',
    HIDE_MESSAGE: 'HIDE_MESSAGE',
    SHOW_LOADING_ANIMATION: 'SHOW_LOADING_ANIMATION',
    HIDE_LOADING_ANIMATION: 'HIDE_LOADING_ANIMATION',
}